import keyMirror  from 'key-mirror';

export default keyMirror({
  SET_CLIENT: null,
  GET_CLIENTS: null,
  GET_CLIENTS_SUCCESS: null,
  GET_CLIENTS_FAILURE: null,
  GET_CLIENT: null,
  GET_CLIENT_SUCCESS: null,
  GET_CLIENT_FAILURE: null,
  GET_PASSPORT_CLIENT_SUCCESS: null,
  GET_PASSPORT_CLIENT_FAILURE: null,
  SAVE_CLIENT:null,
  SAVE_CLIENT_SUCCESS: null,
  SAVE_CLIENT_FAILURE: null,
  GET_REQUESTED: null,
  GET_REQUESTED_SUCCESS: null,
  GET_REQUESTED_FAILURE: null,
  GET_APPROVED: null,
  GET_APPROVED_SUCCESS: null,
  GET_APPROVED_FAILURE: null,
  APPROVE_RESOURCES: null,
  APPROVE_RESOURCES_SUCCESS: null,
  APPROVE_RESOURCES_FAILURE: null,
  DECLINE_RESOURCES: null,
  DECLINE_RESOURCES_SUCCESS: null,
  DECLINE_RESOURCES_FAILURE: null
});
